# Generated by Django 5.2.7 on 2025-10-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_achieved', models.DateField()),
            ],
            options={
                'ordering': ['date_achieved'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Tashi Yangzom', max_length=100)),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('bio', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Profile (Only one entry needed)',
            },
        ),
    ]
